// swift-tools-version: 6.0
import PackageDescription

// Built by scripts/build-engine.sh; linked by path so the linker can't pick the dylib instead.
let engineLib = Context.packageDirectory + "/engine/target/release/libstorrent_engine.a"

let package = Package(
    name: "storrent",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "storrent", targets: ["Storrent"]),
    ],
    targets: [
        // C header + modulemap generated by UniFFI.
        .systemLibrary(name: "storrent_engineFFI"),
        // Swift bindings generated by UniFFI, plus the static Rust library.
        .target(
            name: "StorrentEngine",
            dependencies: ["storrent_engineFFI"],
            swiftSettings: [.swiftLanguageMode(.v5)],
            linkerSettings: [
                .unsafeFlags([engineLib]),
                .linkedFramework("Security"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        // SwiftUI app.
        .executableTarget(
            name: "Storrent",
            dependencies: ["StorrentEngine"],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ]
)
