[package]
name = "storrent-engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "storrent_engine"
crate-type = ["staticlib", "cdylib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
anyhow = "1"
librqbit = "=9.0.1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
uniffi = { version = "0.32.1", features = ["cli"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = "thin"
